name: DevOps Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest

      - name: Build Docker Image
        run: docker build -t devops-demo .

      - name: Run Container
        run: docker run devops-demo

      # - name: Deploy Application
      #   run: docker run devops-demo
